apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-b
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-b
    spec:
      containers:
      - image: anatoliistepaniuk/service-b:latest
        name: service-b
        resources: {}
status: {}
