apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubergang
  labels:
    app: service-a
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-a
    spec:
      containers:
      - image: anatoliistepaniuk/service-a:5.1.0
        name: service-a
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          periodSeconds: 5
        env:
          name: REPLY
          value: "Testing"
#          valueFrom:
#            configMapKeyRef:

