apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-b
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-b
    spec:
      containers:
      - image: anatoliistepaniuk/service-b:4.0.0
        name: service-b
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          failureThreshold: 1
          periodSeconds: 5
