apiVersion: v1
kind: Service
metadata:
  namespace: kubergang
  labels:
    app: service-b
  name: service-b
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: service-b
  type: ClusterIP
status:
  loadBalancer: {}
