apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubergang
  labels:
    app: service-b
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-b
    spec:
      containers:
      - image: anatoliistepaniuk/service-b:5.0.1
        name: service-b
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        env:
          - name: REPLY
            valueFrom:
              configMapKeyRef:
                name: kubergang-config
                key: SERVICE_B_REPLY
