apiVersion: v1
kind: Service
metadata:
  namespace: kubergang
  labels:
    app: front-app
  name: front-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front-app
  type: LoadBalancer
  loadBalancerIP: {{ .Values.frontServiceIp }}
status:
  loadBalancer: {}
