apiVersion: batch/v1
kind: Job
metadata:
  name: helm-test
  namespace: kubergang
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
        - name: tests
          image: anatoliistepaniuk/kubergang-tests:1.0.0
          env:
            - name: SERVICE_A_HOST
              value: http://{{ .Values.serviceAIp }}
            - name: SERVICE_A_REPLY
              value: {{ .Values.serviceAReply }}
            - name: SERVICE_B_REPLY
              value: {{ .Values.serviceBReply }}
      restartPolicy: Never